<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Sensor3.StepDetection\Sensor3.StepDetection.csproj" />
    <ProjectReference Include="..\Sensor3.SensorFusion\Sensor3.SensorFusion.csproj" />
    <ProjectReference Include="..\Sensor3.ActivityRecognition\Sensor3.ActivityRecognition.csproj" />
    <ProjectReference Include="..\Sensor3.CarryingMode\Sensor3.CarryingMode.csproj" />
    <ProjectReference Include="..\Sensor3.Contracts\Sensor3.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
